config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'leaves/approve_leave'
  post 'projects/assign_project'
  delete 'projects/unassign_project'
  get 'status/new'
  get 'status/update'
  get 'users/index', to: 'users#index'
  get 'users/show', to: 'users#show'
  get 'employees', to: 'users#new'
  get 'users/new_employee'
  post 'users/create_employee', to: 'users#create_employee'
  devise_for :users
  # delete '/users/sign_out', to: "home#destroy"
  root to: 'home#index'
  resources :statuses do
    member do
      get 'statuses/daily_task'
    end
  end
  resources :projects
  resources :leaves do
    member do
      get 'leaves/approve_leave'
      get 'leaves/reject_leave'
    end
  end

  namespace :api do 
    namespace :v1 do 
      resources :users
      resources :statuses
      resources :projects
      resources :leaves
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/statuses_controller.rb
# frozen_string_literal: true

class Api::V1::StatusesController < ApplicationController
  
  def index
    @status = Status.all
    render json: @status
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      render json: @status
    end
  end


  private

  def status_params
    params.require(:status).permit(:project_name, :total_hours, :task, :user_id, :manager_id)
  end
end

app/controllers/statuses_controller.rb
# frozen_string_literal: true

class StatusesController < ApplicationController
  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      flash[:notice] = 'Status Uploades'
      redirect_to statuses_path
    else
      flash[:alert] = 'Please Fill all required fields'
      redirect_to new_status_path
    end
  end

  def index
    @status = Status.all
  end

  def daily_task
    @status = Status.find(params[:id])
  end

  private

  def status_params
    params.require(:status).permit(:project_name, :total_hours, :task, :user_id, :manager_id)
  end
end

app/views/statuses/daily_task.html.erb
<div>
 <p> <h4>Employee Name : </h4> <%= @status.user.first_name %> <%= @status.user.last_name %> </p> 
</div>
<div>
 <p> <h4>Email : </h4> <%= @status.user.email %> </p> 
</div>
<div>
  <p><h4>Project</h4><%=@status.project_name%></p> 
</div>
<div>
  <p><h4>Task</h4><%=@status.task%></p>
</div>

app/views/statuses/index.html.erb
<%if admin_user %>
<h1 class=text-center>Daily status</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Employee email</th>
        <th scope="col">Project</th>
        <th scope="col">Hours</th>
        <th scope="col">Task</th>
      </tr>
    </thead>
    <tbody>    
      <% @status.each do |s| %>
        <tr>
          <td> <%= s.user.email %> </td>
          <td> <%= s.project_name %> </td>
          <td> <%= s.total_hours %> </td>
          <td><%= link_to "show",statuses_daily_task_status_path(id: s.id), class:"btn btn-outline-info"%></td>
        
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%else%>
    <h1 class=text-center>Daily status</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Employee email</th>
        <th scope="col">Project</th>
        <th scope="col">Hours</th>
        <th scope="col">Task</th>
      </tr>
    </thead>

    <tbody>
      <% @status.each do |s| %>       
        <tr>        
          <% if s.user_id == current_user.id %>
            <td> <%= s.user.email %> </td>
            <td> <%= s.project_name %> </td>
            <td> <%= s.total_hours %> </td>
            <td> <%= s.task %> </td>          
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%end%>
  

app/views/statuses/new.html.erb
  <div class="col-md-6 col-md-offset-3">
<%= form_with(model: @status, local: true) do |f| %>
      <%= f.label :project_name %>
      <%= f.collection_select :project_name, Project.all, :project_name, :project_name %><br>

      <%= f.label :Task %>
      <%= f.text_field :task, class: 'form-control' %>

      <%= f.label :total_hours %>
      <%= f.number_field :total_hours, class: 'form-control' %>

      <%= f.hidden_field :user_id, value:current_user.id %>

      <%= f.label :manager_id %><br>
      <%= f.collection_select :manager_id, User.all.where(type:"Manager"), :id, :first_name %><br>
      
      <%= f.submit "Upload status", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/statuses/update.html.erb
<h1>Status#update</h1>
<p>Find me in app/views/status/update.html.erb</p>