config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'leaves/approve_leave'
  post 'projects/assign_project'
  delete 'projects/unassign_project'
  get 'status/new'
  get 'status/update'
  get 'users/index', to: 'users#index'
  get 'users/show', to: 'users#show'
  get 'employees', to: 'users#new'
  get 'users/new_employee'
  post 'users/create_employee', to: 'users#create_employee'
  devise_for :users
  # delete '/users/sign_out', to: "home#destroy"
  root to: 'home#index'
  resources :statuses do
    member do
      get 'statuses/daily_task'
    end
  end
  resources :projects
  resources :leaves do
    member do
      get 'leaves/approve_leave'
      get 'leaves/reject_leave'
    end
  end

  namespace :api do 
    namespace :v1 do 
      resources :users
      resources :statuses
      resources :projects
      resources :leaves
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_and_belongs_to_many :projects
  has_many :statuses, dependent: :destroy
  has_many :leaves
  has_many :teammates, class_name: 'User',
                       foreign_key: 'manager_id'
  belongs_to :manager, class_name: 'User',
                       foreign_key: 'manager_id', optional: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  default_scope -> { order(id: :asc) }
  paginates_per 20
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token 
  before_action :set_user, only: %i[show update destroy]

  def index
    @users = User.all
    render json: @users
  end

  def show
    render json: @user
  end

  def create
    @user = User.new(user_params)
    render json: @user if @user.save
  end

  def update 
    @user.update(user_params)
    render json: @user
  end

  def destroy
    @user.destroy
  end

  private

  def set_user 
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.new
  end

  def new_employee
    @user = User.new
  end

  def create_employee
    @user = User.new(employee_params)
    if @user.save
      flash[:notice] = 'Employee Created'
    else
      flash[:alert] = 'please fill all required field'
    end
    redirect_to root_path
  end

  def create
    @user = User.new(user_params)
    redirect_to root_path if @user.save
  end

  def index
    @users = User.page params[:page]
    @projects = Project.all
    @project_id = params[:id]
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :email, :password)
  end

  def employee_params
    params.permit(:first_name, :email, :password)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def admin_user
    current_user.admin?
  end
end

app/views/users/add_new_user.html.erb
   

<h2>Sign up</h2>

<%= form_with url: users_add_new_user_path, method: :post  do |f| %>
  

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>


  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>
  
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/form.htm.erb
<%= form_for User.new , :url => {:action => "add_user"} do |user| %>
  <%=user.email_field :email%>
  <%=user.password_field :password%>
  <%=user.password_field :password_confirmation%>

  <%=user.submit 'add'%>
<%end%>

app/views/users/index.html.erb
<% if admin_user %>
  <%= paginate @users %>
  <h1 class=text-center>All users</h1>
  <table class="table table-striped ">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First name</th>
        <th scope="col">Email</th>
        <th scope="col">Projects</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>  <%= user.id %> </td>
          <td> <%= user.first_name %> </td>
          <td> <%= user.email %> </td>
          <td> <% user.projects.each do |name|%>
                <%= name.project_name%><span>,</span>
               <%end%>
          </td>
           <td><%= link_to "add",projects_assign_project_path(user_id:user.id,project_id:@project_id), method: :post, class: "btn btn-outline-success"%>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @users %>
  <br>


<%else%>
  
    <section>
    <h1 class=text-center> All Projects</h1>
    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">project name</th>
        <th scope="col">status</th>
        <th scope="col">manager Id</th>
      </tr>
    </thead>
    <tbody>
    <%# <% @projects.each do |project| %> 
     <tr>
     <% current_user.projects.each do |project| %>
      
       <td><%= project.id %></td>
      
        <td><%= project.project_name %></td>
        <td><%= project.status %></td>
        <td><%= project.manager_id %> </td>
      </tr>
    
    <% end %>
    </tbody>
    </table>
  </section> 
  <%= paginate @users %>
<%end%>

app/views/users/new_employee.html.erb
<h2>Create Employee </h2>

<%= form_with(url: users_create_employee_path,method: :post, local: true) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>


  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
  </div>
  
  
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/users/show.html.erb
<% if admin_user%>
 <div class="text-center"><h1>welcom to the Admin Page</h1></div>
  
  
  <div class="jumbotron text-center">
    <h1>Create New Employee</h1>
    <p class="lead text-info">  </p>
    <%= link_to "Create",users_new_employee_path, class: "btn btn-lg btn-info"%>
  </div>
  
  <div class="jumbotron text-center">
    <h1>All Projects </h1>
    <p class="lead text-info"> View All Projects</p>
    <%= link_to "Show",projects_path, class: "btn btn-lg btn-info"%>
  </div>
  
  <div class="jumbotron text-center">
    <h1>All Employees </h1>
    <p class="lead text-info"> View All Employees along with their Projects</p>
    <%= link_to "Show",users_index_path, class: "btn btn-lg btn-info"%>
  </div>

  <div class="jumbotron text-center">
    <h1>All Leaves </h1>
    <p class="lead text-info"> View All Employees along with their Projects</p>
    <%= link_to "Show",leaves_path, class: "btn btn-lg btn-info"%>
  </div>

  <div class="jumbotron text-center">
    <h1>See all daily status</h1>
    <p class="lead text-info">  </p>
    <%= link_to "Click here",statuses_path, class: "btn btn-lg btn-info"%>
  </div>
<%end%>





<% if !admin_user%>

 <div class="jumbotron text-center">
    <h1>See your projects</h1>
    <p class="lead text-info">  </p>
    <%= link_to "Click here",users_index_path, class: "btn btn-lg btn-info"%>
  </div>

  <div class="jumbotron text-center">
    <h1>See your leaves</h1>
    <p class="lead text-info">  </p>
    <%= link_to "Click here",leaves_path, class: "btn btn-lg btn-info"%>
  </div>

  <div class="jumbotron text-center">
    <h1>See your daily status</h1>
    <p class="lead text-info">  </p>
    <%= link_to "Click here",statuses_path, class: "btn btn-lg btn-info"%>
  </div>
<%end%>






    